apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: comment-wall
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi