apiVersion: v1
kind: Service
metadata:
  name: comment-wall
  labels:
    app: comment-wall
  namespace: comment-wall
spec:
  selector:
    app: comment-wall
  type: ClusterIP
  ports:
  - name: comment-wall
    protocol: TCP
    port: 80
    targetPort: http